//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSatPortalConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionDb
    {
        public int ActionID { get; set; }
        public string Action { get; set; }
        public string PIC { get; set; }
        public string Remarks { get; set; }
        public string ControlNo { get; set; }
        public string TESID { get; set; }
        public System.DateTime TargetDate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsDeleted { get; set; }
        public bool HasVer { get; set; }
        public string ActionStatus { get; set; }
        public string Type { get; set; }
        public string Dependency { get; set; }
    }
}
