//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSatPortalConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_8DDb
    {
        public int C_8DID { get; set; }
        public byte[] Report { get; set; }
        public string ControlNo { get; set; }
    }
}
