//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSatPortalConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERDb
    {
        public int ERID { get; set; }
        public string ControlNo { get; set; }
        public string WHSESOH { get; set; }
        public string WHSEGOOD { get; set; }
        public string WHSENOGOOD { get; set; }
        public string WHSEDis { get; set; }
        public string IQASOH { get; set; }
        public string IQAGOOD { get; set; }
        public string IQANOGOOD { get; set; }
        public string IQADis { get; set; }
        public string WIPSOH { get; set; }
        public string WIPGOOD { get; set; }
        public string WIPNOGOOD { get; set; }
        public string WIPDis { get; set; }
        public string FGSOH { get; set; }
        public string FGGOOD { get; set; }
        public string FGNOGOOD { get; set; }
        public string FGDis { get; set; }
        public bool Rep { get; set; }
        public string RMAno { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsDeleted { get; set; }
        public string IssueNo { get; set; }
    }
}
