//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSatPortalConsoleApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSatDbEntities : DbContext
    {
        public CSatDbEntities()
            : base("name=CSatDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AccountsDb> AccountsDbs { get; set; }
        public virtual DbSet<ActionDb> ActionDbs { get; set; }
        public virtual DbSet<ART_8D> ART_8D { get; set; }
        public virtual DbSet<ERDb> ERDbs { get; set; }
        public virtual DbSet<IssueDb> IssueDbs { get; set; }
        public virtual DbSet<NotifDb> NotifDbs { get; set; }
        public virtual DbSet<RMADb> RMADbs { get; set; }
        public virtual DbSet<SEDb> SEDbs { get; set; }
        public virtual DbSet<TDDb> TDDbs { get; set; }
        public virtual DbSet<TESDb> TESDbs { get; set; }
        public virtual DbSet<VerDb> VerDbs { get; set; }
        public virtual DbSet<C_8DDb> C_8DDb { get; set; }
        public virtual DbSet<DefDb> DefDbs { get; set; }
    }
}
