//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSatPortalConsoleApp.AppDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ART_8D
    {
        public int ARTID { get; set; }
        public string ControlNo { get; set; }
        public System.DateTime DateValidated { get; set; }
        public System.DateTime DateClosed { get; set; }
    }
}
