//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSatPortalConsoleApp.AppDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueDb
    {
        public int IssueID { get; set; }
        public string IssueCreator { get; set; }
        public string IssueNo { get; set; }
        public System.DateTime DateFound { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Product { get; set; }
        public string SerialNo { get; set; }
        public string AffectedPN { get; set; }
        public int Qty { get; set; }
        public string Desc { get; set; }
        public string ProbDesc { get; set; }
        public byte[] ClientRep { get; set; }
        public string ValNo { get; set; }
        public System.DateTime DateAck { get; set; }
        public bool ValidatedStatus { get; set; }
        public string ValidationRepSum { get; set; }
        public string NRMA { get; set; }
        public string ValRes { get; set; }
        public byte[] Report { get; set; }
        public string ControlNumber { get; set; }
        public System.DateTime DateVdal { get; set; }
        public bool Acknowledged { get; set; }
        public bool HasTES { get; set; }
        public bool HasCR { get; set; }
        public bool isDeleted { get; set; }
        public string NeedRMA { get; set; }
        public string Validator { get; set; }
        public byte[] EmailSnip { get; set; }
        public string FFFS { get; set; }
        public string Requirement { get; set; }
        public bool Has8D { get; set; }
        public bool Verified { get; set; }
    }
}
