//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSatPortalConsoleApp.AppDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDDb
    {
        public int TDID { get; set; }
        public int ActionID { get; set; }
        public System.DateTime TD { get; set; }
        public string ControlNo { get; set; }
        public string Status { get; set; }
    }
}
