//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSatPortalConsoleApp.AppDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerDb
    {
        public int VerID { get; set; }
        public int ActionID { get; set; }
        public string ControlNo { get; set; }
        public string Status { get; set; }
        public byte[] Files { get; set; }
        public System.DateTime DateVer { get; set; }
        public System.DateTime StatusDate { get; set; }
        public string Result { get; set; }
        public bool IsDeleted { get; set; }
        public string RCType { get; set; }
        public string Verificator { get; set; }
    }
}
